// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DexTradesOutput {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<TradeData>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Output {
    #[prost(message, repeated, tag="1")]
    pub data: ::prost::alloc::vec::Vec<MevBundle>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MevBundle {
    #[prost(string, required, tag="1")]
    pub block_date: ::prost::alloc::string::String,
    #[prost(int64, required, tag="2")]
    pub block_time: i64,
    #[prost(uint64, required, tag="3")]
    pub block_slot: u64,
    #[prost(string, required, tag="4")]
    pub signer: ::prost::alloc::string::String,
    #[prost(string, required, tag="5")]
    pub trader: ::prost::alloc::string::String,
    #[prost(enumeration="MevType", required, tag="6")]
    pub mev_type: i32,
    #[prost(message, repeated, tag="8")]
    pub trades: ::prost::alloc::vec::Vec<TradeData>,
    #[prost(string, optional, tag="9")]
    pub bundle_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MevBundleSummary {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeData {
    #[prost(string, required, tag="1")]
    pub block_date: ::prost::alloc::string::String,
    #[prost(int64, required, tag="2")]
    pub block_time: i64,
    #[prost(uint64, required, tag="3")]
    pub block_slot: u64,
    #[prost(string, required, tag="4")]
    pub tx_id: ::prost::alloc::string::String,
    #[prost(int64, required, tag="5")]
    pub tx_index: i64,
    #[prost(string, required, tag="6")]
    pub signer: ::prost::alloc::string::String,
    #[prost(string, required, tag="7")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(string, required, tag="8")]
    pub base_mint: ::prost::alloc::string::String,
    #[prost(string, required, tag="9")]
    pub quote_mint: ::prost::alloc::string::String,
    #[prost(string, required, tag="10")]
    pub base_vault: ::prost::alloc::string::String,
    #[prost(string, required, tag="11")]
    pub quote_vault: ::prost::alloc::string::String,
    #[prost(double, required, tag="12")]
    pub base_amount: f64,
    #[prost(double, required, tag="13")]
    pub quote_amount: f64,
    #[prost(bool, required, tag="14")]
    pub is_inner_instruction: bool,
    #[prost(uint32, required, tag="15")]
    pub instruction_index: u32,
    #[prost(string, required, tag="16")]
    pub instruction_type: ::prost::alloc::string::String,
    #[prost(uint32, required, tag="17")]
    pub inner_instruxtion_index: u32,
    #[prost(string, required, tag="18")]
    pub outer_program: ::prost::alloc::string::String,
    #[prost(string, required, tag="19")]
    pub inner_program: ::prost::alloc::string::String,
    #[prost(uint64, required, tag="20")]
    pub txn_fee_lamports: u64,
    #[prost(int64, required, tag="21")]
    pub signer_lamports_change: i64,
    #[prost(string, required, tag="22")]
    pub trader: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="23")]
    pub outer_executing_accounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int64, required, tag="24")]
    pub trader_lamports_change: i64,
    #[prost(message, repeated, tag="25")]
    pub trader_token_balance_changes: ::prost::alloc::vec::Vec<TraderTokenBalanceChange>,
    #[prost(string, optional, tag="26")]
    pub bundle_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraderTokenBalanceChange {
    #[prost(string, required, tag="1")]
    pub mint: ::prost::alloc::string::String,
    #[prost(double, required, tag="2")]
    pub amount: f64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MevType {
    Arbitrage = 1,
    Sandwich = 2,
}
impl MevType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            MevType::Arbitrage => "ARBITRAGE",
            MevType::Sandwich => "SANDWICH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARBITRAGE" => Some(Self::Arbitrage),
            "SANDWICH" => Some(Self::Sandwich),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
